### ISSUE TITLE
Not working for Larger Text

### ISSUE THREAD

**Issue by siddharthsuneel** [AugustRush/UICollectionView-ARDynamicHeightLayoutCell#10]
Hello @AugustRush  I have trying to implement this, but not getting exact height for larger text.
I have attached a text file containing the string I was using.
Please find the attachment.
[Dummy Text String.zip](https://github.com/AugustRush/UICollectionView-ARDynamicHeightLayoutCell/files/132112/Dummy.Text.String.zip)

**Comment by AugustRush** [comment]
This may be a system bug, i have update my demo. you need set a correct 'preferredMaxLayoutWidth'  for multi-line UIlabel. please see my demo detail.

**Comment by siddharthsuneel** [comment]
@AugustRush I really appreciate your effort, But if you again run this demo you can see that when cell's content label is having the larger text, complete text is not being displayed some lines from the text are missing.
Please take a look.

**Comment by AugustRush** [comment]
please see my last commit,  complete text is not being displayed some lines because i set a wrong value to multi-line 'contentLabel', sorry for this.

**Comment by siddharthsuneel** [comment]
Great, It worked now... 
Thanks. :)
