### ISSUE TITLE
Load the network data for the first time, pictures showed not to come out, after the refresh can display, how to solve？

### ISSUE THREAD

**Issue by sany620** [AugustRush/UICollectionView-ARDynamicHeightLayoutCell#13]
Load the network data for the first time, pictures showed not to come out, after the refresh can display, how to solve？
code：
` CGFloat width = (SCREENWIDTH - 30)/2;
        return [collectionView ar_sizeForCellWithIdentifier:@"RecommendedCell"
                                                  indexPath:indexPath
                                                 fixedWidth:width configuration:^(id cell) {
                                                     RecommendedListResultModel *listData =self.m_newArr[indexPath.row];
                                                     [cell setCellData:listData];`

**Comment by AugustRush** [comment]
What did you use to download images? it's strange.

**Comment by sany620** [comment]
Is to load the network images, not local。Can provide the solution?

**Comment by AugustRush** [comment]
The 'ImageView ' need constraint to confirm size itself, so you can add fixed size constraints as default size and update it after network images has loaded.

**Comment by sany620** [comment]
thanks
