### ISSUE TITLE
How to use without storyboard?

### ISSUE THREAD

**Issue by sahil263** [AugustRush/UICollectionView-ARDynamicHeightLayoutCell#2]
I am using xibs in my project. I followed your guidelines. But, still I am not able to make it work with xib.

Please provide the details, for how to add it with xib.

**Comment by AugustRush** [comment]
Can you tell me the details of errors?

发自我的 iPhone

**Comment by sahil263** [comment]
The collection view cells doesn't display any data...

**Comment by AugustRush** [comment]
You should registering a cell's nib if you use nib,or registering a cell's class if you have no nib,don't forget set the reuse identifier.my demo is using a nib without storyboard.

发自我的 iPhone

**Comment by sahil263** [comment]
Yes, I have registered the cell's nib in `viewDidLoad` of my `ViewController` class.
I'll try to attach my code here (when I reach my work place).

**Comment by AugustRush** [comment]
Maybe your cell's autolayout constant isn't correctly.

发自我的 iPhone

**Comment by sahil263** [comment]
@AugustRush  Ok, I'll look into it throughly.
