### ISSUE TITLE
crush in getting cached size

### ISSUE THREAD

**Issue by zjr999** [AugustRush/UICollectionView-ARDynamicHeightLayoutCell#4]
when there are two sections,the first use fixed size,and the second use ARDynamicHeightLayoutCell,it will crush.I see it crush in [self sizeCache][indexPath.section] for NSRangeException. change indexPath.section to 0 can solve this question.

**Comment by AugustRush** [comment]
thanks,I will check it.

发自我的 iPhone

**Comment by fenomenar9** [comment]
The crash still persist. Please check this.

**Comment by AugustRush** [comment]
I just fixed it ,sorry! please check it.
